### ISSUE TITLE
Trailing Commas Don't Throw Exceptions

### ISSUE THREAD

**Issue by jacobp100** [SublimeLinter/SublimeLinter-json#11]
They aren't valid in JSON.

**Comment by skj3gg** [comment]
Are you referring to trailing commas like the example below, where
```
{
    "banana": true,
}
```
Are you getting any errors in the file?


On a side note, This isn't really an issue of `SL-json`, it uses Python's (or with Sublime-specific file extensions, Sublime's) builtin JSON **parser** instead of a linter, and displaying the first error it comes across.  So the output wouldn't be "Trailing Comma", but instead, an error caused by parsing something with a trailing comma, `Expecting property name enclosed in double quotes`

**Comment by skj3gg** [comment]
Did this answer your issue @jacobp100?

**Comment by bixibu** [comment]
+1 on that.

Some plugin (Html/JS/CSS Prettify for example) can't load JSON files when there is a trailing coma, and it's hard to figure it out when the json file seems OK (no lint error, but error in the console)

**Comment by truhlikfredy** [comment]
I'm not even getting the "Expecting property name enclosed in double quotes" which would be fine, basically if I have strict lint on I would expect it would validate in such manner it would be considered across all platforms. If there would be extra settings just to enable this validation it would be fine. I know many languages are fine with the comman, but not all and that is the problem.

**Comment by truhlikfredy** [comment]
One solution is to uninstall SublimeLinter-json and install JSHint instead which can validate the json the way we need (extra comma is detected), jshint requires node but probably people with this issue have node already.

**Comment by 0x80** [comment]
Having this problem also. @truhlikfredy I've been using eslint for years and wouldn't like to go back to jshint. Do you know if I restrict jshint to only json files?

**Comment by 0x80** [comment]
I found a json plugin for eslint but couldn't figure out how to pass the json extension to the eslint CLI properly for the linter settings. I'm giving VSCode a try now, since these things just work out of the box  :)

**Comment by braver** [comment]
I can't reproduce any of this in recent versions of the packages and ST3. Also, JavaScript linters tend to lint JSON very well too.
